Repository JiPyoTak/plandar-client, pull requests merged in 2023-06, with the labels that each got.

#77 시간 일정을 보여주는 방식을 변경하고 제대로 렌더링 하도록 변경
  src/components/timetable/view/TimetableCellColumn.tsx
  src/components/timetable/view/TimetablePlanColumn.tsx
  src/components/timetable/view/TimetableSelect.tsx
  src/components/timetable/view/index.tsx
  src/constants/mock.ts
  src/hooks/useTimetableViewMoment.ts
  src/plan/Plan.ts
  src/plan/TimePlanManager.ts
  src/stories/plan/createPlanMock.ts
  src/stories/timetable/DayTimetable.stories.tsx
  src/stories/timetable/WeekTimetable.stories.tsx
  src/utils/date/getTimeMinute.ts
  src/utils/plan/getColumnPlans.ts
Labels: BUG, FEATURE

#69 사이드바 drawer 기능 구현
  src/assets/hamburger-icon.svg
  src/components/buttons/HamburgerButton.tsx
  src/components/icons/index.ts
  src/components/sidebar/index.tsx
  src/pages/index.tsx
  src/stores/drawer.ts
  src/styles/home.ts
Labels: FEATURE

#82 시간 일정 드래그 최적화 및 부가 기능 추가
  src/components/calendars/large/CalendarLayer.tsx
  src/components/plan/TimePlan.tsx
  src/components/timetable/TimetableTimeline.tsx
  src/components/timetable/index.tsx
  src/components/timetable/view/TimetableCellColumn.tsx
  src/components/timetable/view/TimetablePlanColumn.tsx
  src/components/timetable/view/TimetableSelect.tsx
  src/components/timetable/view/index.tsx
  src/hooks/usePlanDrag.ts
  src/stores/plan/focusedPlan.ts
  src/styles/timetable.ts
  src/utils/plan/getFocusedTimePlan.ts
  src/utils/plan/timePlanHandlers.ts
Labels: BUG, FEATURE

#80 Plan API 연결 및 hook 생성
  src/apis/plan.ts
  src/hooks/rq/plan.ts
  src/utils/date/getFirstAndLastWeek.ts
  src/utils/date/getFormattedDate.ts
  src/utils/date/getStartAndEndDate.ts
  src/utils/date/getYMDByDateFormat.ts
Labels: FEATURE

#87 작은 달력은 다른 컴포넌트에서 사용 가능하도록 변경
  src/components/calendars/small/index.tsx
  src/components/sidebar/SmallCalendar.tsx
  src/components/sidebar/index.tsx
Labels: REFACTOR

#90 Dropdown 여닫는 속도 개선
  src/components/common/dropdown/index.tsx
Labels: FEATURE

#91 일정 생성 모달창 api 연결
  src/apis/axios/index.ts
  src/components/modal/plan/PlanTag.tsx
  src/components/modal/plan/index.tsx
  src/hooks/rq/plan.ts
Labels: FEATURE

#98 큰 달력 일정 API 연결
  src/apis/plan.ts
  src/components/calendars/large/CalendarLayer.tsx
  src/components/calendars/large/CalendarOverlay.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/calendars/large/CalendarWeek.tsx
  src/hooks/rq/plan.ts
  src/hooks/usePlanDrag.ts
  src/plan/Plan.ts
  src/stores/plan/focusedPlan.ts
  src/types/rq/plan.d.ts
Labels: FEATURE, NOFIX

#99 일간 달력 - 종일 일정 드래그 기능
  src/components/calendars/large/CalendarLayer.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/plan/DayPlan.tsx
  src/components/timetable/TimetableHeader.tsx
  src/components/timetable/TimetableScroller.tsx
  src/components/timetable/index.tsx
  src/components/timetable/view/TimetableAllDay.tsx
  src/components/timetable/view/columns/TimetableCellColumn.tsx
  src/components/timetable/view/columns/TimetablePlanColumn.tsx
  src/components/timetable/view/columns/TimetableSelected.tsx
  src/components/timetable/view/columns/TimetableTimeline.tsx
  src/components/timetable/view/columns/index.tsx
  src/components/timetable/view/index.tsx
  src/hooks/rq/plan.ts
  src/hooks/usePlanDrag.ts
  src/plan/DaysPlanManager.ts
  src/utils/date/getYMDByDateFormat.ts
Labels: BUG, FEATURE

#105 Storybook에서 API 모킹하기 위한 MSW 설정
  .eslintrc
  .storybook/preview.jsx
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/stories/apis/msw/index.ts
  tsconfig.json
Labels: CHORE

#101 일정생성 모달창 날짜 선택 기능 구현
  src/apis/tag.ts
  src/components/calendars/small/CalendarView.tsx
  src/components/modal/plan/DateDisplay.tsx
  src/components/modal/plan/PlanDate/DatePicker.tsx
  src/components/modal/plan/PlanDate/TimeInput.tsx
  src/components/modal/plan/PlanDate/TimeOptionList.tsx
  src/components/modal/plan/PlanDate/index.tsx
  src/components/modal/plan/PlanTag.tsx
  src/components/modal/plan/index.tsx
  src/hooks/usePlanDateState.ts
  src/hooks/usePlanDrag.ts
  src/plan/Plan.ts
  src/types/rq/plan.d.ts
  src/types/rq/tag.d.ts
  src/types/time.d.ts
  src/utils/date/getTimeString.ts
  src/utils/plan/isValidPlan.ts
Labels: FEATURE

#104 Hovered/Selected modal 생성
  package.json
  src/components/buttons/TagButton.tsx
  src/components/calendars/large/CalendarLayer.tsx
  src/components/common/modal/Category.tsx
  src/components/common/modal/Timestamp.tsx
  src/components/common/modal/styles.ts
  src/components/modal/plan/Hovered/index.tsx
  src/components/modal/plan/PlanCategory.tsx
  src/components/modal/plan/Selected/index.tsx
  src/hooks/useDebounce.ts
  src/hooks/useEffectModal.ts
  src/stores/plan/hoveredPlan.ts
  src/stores/plan/selectedPlan.ts
  src/stories/modals/HoveredModal.stories.tsx
  src/stories/modals/SelectedModal.stories.tsx
Labels: FEATURE, REFACTOR

#107 Large Calendar API Mocking 및 테스트 환경 조성
  src/components/calendars/large/CalendarCell.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/calendars/large/CalendarWeek.tsx
  src/components/timetable/view/index.tsx
  src/constants/mock.ts
  src/plan/DaysPlanManager.ts
  src/stories/apis/data/plan.ts
  src/stories/apis/plan.ts
  src/stories/calendars/LargeCalendar.stories.tsx
  src/stories/modals/HoveredModal.stories.tsx
  src/stories/modals/SelectedModal.stories.tsx
  src/stories/plan/createPlanMock.ts
  src/stories/timetable/DayTimetable.stories.tsx
  src/stories/timetable/WeekTimetable.stories.tsx
Labels: FEATURE, TEST

#108 월간 달력에서 TimePlan 렌더링
  src/components/calendars/large/CalendarCell.tsx
  src/components/plan/DayTimePlan.tsx
  src/stories/calendars/LargeCalendar.stories.tsx
Labels: FEATURE

#110 Large Calendar Selected Plan Modal적용
  src/assets/trashcan-icon.svg
  src/components/calendars/large/CalendarCell.tsx
  src/components/calendars/large/CalendarLayer.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/common/modal/Timestamp.tsx
  src/components/icons/index.ts
  src/components/modal/index.tsx
  src/components/modal/plan/Hovered/index.tsx
  src/components/modal/plan/Selected/index.tsx
  src/components/plan/DayPlan.tsx
  src/hooks/useEffectModal.ts
  src/hooks/usePlanDrag.ts
  src/pages/index.tsx
  src/utils/date/formatDate.ts
Labels: FEATURE

#111 Timetable Plans를 React-Query로 받아오도록 설정
  src/components/timetable/TimetableHeader.tsx
  src/components/timetable/view/index.tsx
  src/stories/apis/data/plan.ts
  src/stories/timetable/DayTimetable.stories.tsx
  src/stories/timetable/WeekTimetable.stories.tsx
Labels: FEATURE

#115 개발 도중 생긴 Storybook 오류들 고치기
  src/stories/buttons/Checkbox.stories.tsx
  src/stories/buttons/DirectionButtons.stories.tsx
  src/stories/buttons/TodayButton.stories.tsx
  src/stories/calendars/SmallCalendar.stories.tsx
  src/stories/plan/PlanMemo.stories.tsx
Labels: FEATURE

#116 Plan Drag시 발생하던 오류 수정
  src/components/calendars/large/CalendarView.tsx
  src/components/timetable/TimetableAllDay.tsx
  src/components/timetable/view/TimetableAllDay.tsx
  src/plan/Plan.ts
  src/utils/plan/planViewHandlerToMonth.ts
  src/utils/plan/timePlanHandlers.ts
Labels: BUG, REFACTOR

#120 일정 생성 모달창 버그 해결
  src/components/common/dropdown/DropdownController.tsx
  src/components/modal/plan/PlanCategory.tsx
  src/components/modal/plan/PlanDate/TimeInput.tsx
  src/components/modal/plan/PlanMemo.tsx
  src/components/modal/plan/PlanTag.tsx
  src/components/modal/plan/index.tsx
  src/components/sidebar/classifier/ClassifierTitle.tsx
  src/stories/modals/PlanModal.stories.tsx
  src/styles/planModal.ts
Labels: BUG

#119 토스트 메시지 구현
  src/components/toast/Toast.tsx
  src/components/toast/ToastContainer.tsx
  src/components/toast/ToastTransition.tsx
  src/hooks/useToast.ts
  src/hooks/useToastContainer.ts
  src/main.tsx
  src/styles/toast.ts
  src/toast/eventManager.ts
  src/toast/index.ts
  src/toast/toast.ts
  src/types/toast.d.ts
  src/utils/toast/collapseToast.ts
  src/utils/toast/propValidator.ts
Labels: FEATURE
