Repository JiPyoTak/plandar-client, pull requests merged in 2023-08, with the labels that each got.

#157 Category 관련 기능 추가 업데이트
  src/apis/category.ts
  src/components/common/classifier/ClassifierTitle.tsx
  src/components/common/modal/Category.tsx
  src/components/core/dropdown/DropdownController.tsx
  src/components/home/sidebar/content/classifier/CategoryClassifier.tsx
  src/components/home/sidebar/content/classifier/category/CategoryClassifierItem.tsx
  src/components/home/sidebar/content/classifier/category/CategoryClassifierTitle.tsx
  src/components/home/sidebar/content/classifier/category/index.tsx
  src/components/home/sidebar/content/index.tsx
  src/components/modal/category/index.tsx
  src/components/modal/plan/create/index.tsx
  src/components/modal/plan/hover/index.tsx
  src/components/modal/plan/select/index.tsx
  src/hooks/query/category.ts
  src/stores/modal/category.ts
  src/stories/modals/CategoryModal.stories.tsx
  src/stories/sidebar/CategoryClassifier.stories.tsx
Labels: BUG, FEATURE

#159 화면 크기 변경시 모달 좌표 재계산
  src/components/modal/plan/hover/index.tsx
  src/components/modal/plan/select/index.tsx
  src/hooks/useEffectModal.ts
  src/hooks/usePlanActive.ts
  src/hooks/useWindowResize.ts
  src/stores/plan/hoveredPlan.ts
  src/stores/plan/selectedPlan.ts
  src/stores/window-size.ts
  src/stories/modals/HoveredModal.stories.tsx
  src/stories/modals/SelectedModal.stories.tsx
  src/utils/calendar/getPositionByViewPort.ts
  src/utils/debounce.ts
  vite.config.ts
Labels: FEATURE, REFACTOR

#161 README.md v1.0.0
  README.md
Labels: DOC

#162 README.md v1.0.1 (How To Use 잘못된 점 수정)
  README.md
Labels: DOC

#163 hook 패턴을 통해 일정에 대한 중복 기능 분리 및 기존 하위 컴포넌트에서 호출하던 함수를 상위 컴포넌트로 이동
  src/components/common/plan/DayPlan.tsx
  src/components/home/main/calendar/CalendarCell.tsx
  src/components/home/main/calendar/CalendarLayer.tsx
  src/components/home/main/calendar/CalendarTimePlans.tsx
  src/components/home/main/calendar/CalendarView.tsx
  src/components/home/main/calendar/CalendarWeek.tsx
  src/components/home/main/timetable/view/TimetableAllDay.tsx
  src/components/home/main/timetable/view/columns/TimetableCellColumn.tsx
  src/components/home/main/timetable/view/columns/TimetablePlanColumn.tsx
  src/components/modal/plan/create/index.tsx
  src/components/modal/plan/select/index.tsx
  src/hooks/usePlanPreviewEvent.ts
  src/stores/date.ts
Labels: REFACTOR

#164 Timetable 일정 버그 수정
  src/components/common/plan/TimePlan.tsx
  src/components/home/main/timetable/view/TimetableAllDay.tsx
  src/components/home/main/timetable/view/index.tsx
  src/components/modal/plan/create/plan-date/TimeInput.tsx
  src/core/plan/TimePlanManager.ts
  src/stores/plan/focusedPlan.ts
  src/styles/timetable.ts
  src/utils/plan/getColumnPlans.ts
  src/utils/plan/timePlanHandlers.ts
Labels: BUG, REFACTOR

#168 modal open state 생성
  src/components/core/buttons/PlusButton.tsx
  src/components/modal/plan/create/index.tsx
  src/components/modal/plan/select/index.tsx
  src/hooks/usePlanDrag.ts
  src/stores/modal/create.ts
  src/stores/plan/focusedPlan.ts
  src/utils/plan/createInitPlan.ts
Labels: FEATURE, REFACTOR
