Repository JiPyoTak/plandar-client, pull requests merged in 2023-07, with the labels that each got.

#124 토스트 메시지 사용
  src/App.tsx
  src/components/buttons/ProfileButton/ProfilePopup.tsx
  src/components/common/ColorPicker.tsx
  src/components/modal/plan/Candidates/CandidateItem.tsx
  src/components/modal/plan/Selected/index.tsx
  src/components/modal/plan/category/SelectedCategoryDisplay.tsx
  src/components/modal/plan/index.tsx
  src/components/sidebar/CategoryClassifier.tsx
  src/hooks/usePlanDrag.ts
  src/styles/category.ts
Labels: FEATURE

#123 일정에 따라 Sidebar 렌더링 및 컨트롤 활성화
  src/components/calendars/large/CalendarView.tsx
  src/components/sidebar/CategoryClassifier.tsx
  src/components/sidebar/TagClassifier.tsx
  src/components/sidebar/TypeClassifier.tsx
  src/components/sidebar/classifier/ClassifierItem.tsx
  src/components/sidebar/index.tsx
  src/components/timetable/view/index.tsx
  src/hooks/useClassifiedPlans.ts
  src/stores/classifier/tag.ts
  src/stores/classifier/type.ts
  src/stories/apis/category.ts
  src/stories/apis/data/category.ts
  src/stories/apis/data/index.ts
  src/stories/apis/data/plan.ts
  src/stories/sidebar/CategoryClassifier.stories.tsx
  src/stories/sidebar/TagClassifier.stories.tsx
  src/stories/sidebar/TypeClassifier.stories.tsx
  src/stories/utils/createRandomColor.ts
Labels: FEATURE

#122 Large Calendar TimePlan 추가
  src/components/calendars/large/CalendarCell.tsx
  src/components/calendars/large/CalendarLayer.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/common/calendar/TimePlanList.tsx
  src/components/modal/plan/Selected/index.tsx
  src/components/plan/DayTimePlan.tsx
  src/hooks/usePlanActive.ts
  src/main.tsx
  src/utils/plan/dummy.ts
Labels: FEATURE

#126 Create Modal 디렉터리 구조 변경
  src/components/modal/plan/Created/PlanAllDay.tsx
  src/components/modal/plan/Created/PlanCategory.tsx
  src/components/modal/plan/Created/PlanColorPicker.tsx
  src/components/modal/plan/Created/PlanMemo.tsx
  src/components/modal/plan/Created/PlanTag.tsx
  src/components/modal/plan/Created/PlanTitleInput.tsx
  src/components/modal/plan/Created/index.tsx
  src/pages/index.tsx
  src/stores/user.ts
  src/stories/modals/PlanModal.stories.tsx
  src/stories/plan/PlanCategory.stories.tsx
  src/stories/plan/PlanMemo.stories.tsx
  src/stories/plan/PlanTag.stories.tsx
Labels: REFACTOR

#129 Timetable SelectedModal, HoveredModal 적용
  src/App.tsx
  src/components/modal/plan/Selected/index.tsx
  src/components/plan/DayPlan.tsx
  src/components/plan/TimePlan.tsx
  src/components/timetable/view/TimetableAllDay.tsx
  src/components/timetable/view/columns/TimetablePlanColumn.tsx
  src/components/timetable/view/columns/index.tsx
  src/hooks/useClassifiedPlans.ts
Labels: FEATURE

#132 TimePlan props 여부 변경
  src/components/plan/TimePlan.tsx
Labels: BUG

#130 로고 만들기 및 적용하기
  index.html
  public/images/android-icon-144x144.png
  public/images/android-icon-192x192.png
  public/images/android-icon-36x36.png
  public/images/android-icon-48x48.png
  public/images/android-icon-72x72.png
  public/images/android-icon-96x96.png
  public/images/apple-icon-114x114.png
  public/images/apple-icon-120x120.png
  public/images/apple-icon-144x144.png
  public/images/apple-icon-152x152.png
  public/images/apple-icon-180x180.png
  public/images/apple-icon-57x57.png
  public/images/apple-icon-60x60.png
  public/images/apple-icon-72x72.png
  public/images/apple-icon-76x76.png
  public/images/apple-icon-precomposed.png
  public/images/apple-icon.png
  public/images/favicon-16x16.png
  public/images/favicon-32x32.png
  public/images/favicon-96x96.png
  public/images/favicon.ico
  public/images/ms-icon-144x144.png
  public/images/ms-icon-150x150.png
  public/images/ms-icon-310x310.png
  public/images/ms-icon-70x70.png
  public/manifest.json
  src/assets/logo-icon.svg
  src/components/icons/index.ts
  src/components/logo/index.tsx
Labels: FEATURE

#134 전체적인 디자인 개선
  src/assets/calendar-icon.svg
  src/assets/home-icon.svg
  src/assets/logo-icon.svg
  src/assets/only-logo-icon.svg
  src/assets/tag-icon.svg
  src/components/buttons/HamburgerButton.tsx
  src/components/buttons/ProfileButton/ProfileImage.tsx
  src/components/buttons/TagButton.tsx
  src/components/common/calendar/CalendarDay.tsx
  src/components/common/calendar/CalendarHeader/index.tsx
  src/components/icons/index.ts
  src/components/logo/index.tsx
  src/components/modal/index.tsx
  src/components/plan/DayPlan.tsx
  src/components/plan/TimePlan.tsx
  src/components/sidebar/SidebarIcons.tsx
  src/components/sidebar/content/CategoryClassifier.tsx
  src/components/sidebar/content/SmallCalendar.tsx
  src/components/sidebar/content/TagClassifier.tsx
  src/components/sidebar/content/TypeClassifier.tsx
  src/components/sidebar/content/UserInfo.tsx
  src/components/sidebar/content/classifier/ClassifierItem.tsx
  src/components/sidebar/content/classifier/ClassifierTitle.tsx
  src/components/sidebar/content/index.tsx
  src/components/sidebar/index.tsx
  src/components/timetable/view/columns/TimetableCellColumn.tsx
  src/constants/index.ts
  src/pages/index.tsx
  src/stores/drawer.ts
  src/stores/menu.ts
  src/stories/calendars/SmallCalendar.stories.tsx
  src/stories/sidebar/CategoryClassifier.stories.tsx
  src/stories/sidebar/TagClassifier.stories.tsx
  src/stories/sidebar/TypeClassifier.stories.tsx
  src/styles/home.ts
  src/styles/planModal.ts
  src/styles/sidebar.ts
  src/styles/theme.ts
  src/utils/plan/createInitPlan.ts
Labels: FEATURE, REFACTOR

#139 Timetable 일정 관련 버그 수정 (스크롤, 선택 등)
  src/components/common/plan/TimePlan.tsx
  src/components/home/main/timetable/TimetableHeader.tsx
  src/components/home/main/timetable/TimetableScroll.tsx
  src/components/home/main/timetable/index.tsx
  src/components/home/main/timetable/view/TimetableAllDay.tsx
  src/components/home/main/timetable/view/columns/TimetablePlanColumn.tsx
  src/components/home/main/timetable/view/columns/TimetableSelected.tsx
  src/components/home/main/timetable/view/columns/index.tsx
  src/components/modal/ModalPortal.tsx
  src/components/modal/cateogry/index.tsx
  src/components/modal/plan/create/index.tsx
  src/components/modal/plan/hover/index.tsx
  src/components/modal/plan/select/index.tsx
  src/hooks/useTimetableScroll.ts
  src/pages/index.tsx
  src/stories/calendars/LargeCalendar.stories.tsx
  src/stories/modals/PlanModal.stories.tsx
Labels: BUG

#142 일정 생성 모달 기능 추가 및 스타일 변경
  .eslintignore
  .github/workflows/deploy.yml
  Dockerfile
  src/components/home/sidebar/content/classifier/CategoryClassifier.tsx
  src/components/modal/category/index.tsx
  src/components/modal/plan/create/PlanCategory.tsx
  src/components/modal/plan/create/PlanMemo.tsx
  src/components/modal/plan/create/PlanTag.tsx
  src/components/modal/plan/create/candidates/CandidateItem.tsx
  src/components/modal/plan/create/candidates/CandidateList.tsx
  src/components/modal/plan/create/index.tsx
  src/components/modal/plan/create/plan-date/DatePicker.tsx
  src/components/modal/plan/create/plan-date/TimeInput.tsx
  src/components/modal/plan/create/plan-date/TimeOptionList.tsx
  src/components/modal/plan/create/plan-date/index.tsx
  src/hooks/modal/usePlanModalCategory.ts
  src/hooks/usePlanDateState.ts
  src/stories/modals/CategoryModal.stories.tsx
  src/styles/scroll.ts
  src/utils/calendar/dayHandler.ts
Labels: FEATURE, REFACTOR

#145 일, 주 달력에서도 사이드바 태그가 월 단위로 보여주던 버그 수정
  src/components/home/sidebar/content/classifier/TagClassifier.tsx
  src/stores/test.ts
  src/stories/sidebar/TagClassifier.stories.tsx
Labels: BUG

#148 사이드 바 View 변경사항 추가 - 스켈레톤 및 빈 화면
  src/components/common/classifier/ClassifierGuide.tsx
  src/components/common/classifier/ClassifierItem.tsx
  src/components/home/sidebar/content/classifier/CategoryClassifier.tsx
  src/components/home/sidebar/content/classifier/TagClassifier.tsx
  src/stories/apis/data/index.ts
  src/stories/sidebar/CategoryClassifier.stories.tsx
  src/styles/index.ts
Labels: FEATURE

#149 Modal 내부 Popup이 Modal을 벗어나지 못하던 오류 수정
  src/components/common/ColorPicker.tsx
  src/components/common/color-picker/ColorList.tsx
  src/components/common/color-picker/PickButton.tsx
  src/components/common/color-picker/index.tsx
  src/components/common/mini-calendar/CalendarView.tsx
  src/components/common/modal/ModalBackground.tsx
  src/components/modal/ModalPortal.tsx
  src/components/modal/category/index.tsx
  src/components/modal/plan/create/PlanAllDay.tsx
  src/components/modal/plan/create/PlanColorPicker.tsx
  src/components/modal/plan/create/category/SelectedCategoryDisplay.tsx
  src/components/modal/plan/create/index.tsx
  src/components/modal/plan/create/plan-date/DatePicker.tsx
  src/components/modal/plan/create/plan-date/TimeInput.tsx
  src/components/modal/plan/create/plan-date/index.tsx
  src/components/modal/plan/hover/index.tsx
  src/components/modal/plan/select/index.tsx
  src/hooks/modal/useModalPopupPositon.ts
  src/stories/common/ColorPicker.stories.tsx
  src/utils/plan/createInitPlan.ts
Labels: BUG, REFACTOR

#150 전역 Date 상태가 범위를 가질 수 있도록 추가
  src/components/core/buttons/CalendarUnitButton.tsx
  src/components/home/main/header/HeaderButtons.tsx
  src/components/home/main/timetable/index.tsx
  src/components/home/sidebar/content/classifier/TagClassifier.tsx
  src/constants/index.ts
  src/hooks/useClassifiedPlans.ts
  src/hooks/useRangedPlans.ts
  src/pages/index.tsx
  src/stores/date.ts
  src/stories/calendars/LargeCalendar.stories.tsx
  src/stories/calendars/SmallCalendar.stories.tsx
  src/stories/sidebar/TagClassifier.stories.tsx
  src/stories/timetable/DayTimetable.stories.tsx
  src/stories/timetable/WeekTimetable.stories.tsx
Labels: FEATURE, REFACTOR
