Repository JiPyoTak/plandar-client, pull requests merged in 2023-05, with the labels that each got.

#51 일정생성 모달 UI 구현
  src/components/buttons/Checkbox.tsx
  src/components/modal/plan/DateDisplay.tsx
  src/components/modal/plan/PlanAllDay.tsx
  src/components/modal/plan/PlanCategory.tsx
  src/components/modal/plan/PlanMemo.tsx
  src/components/modal/plan/PlanTag.tsx
  src/components/modal/plan/category/CategoryCreateForm.tsx
  src/components/modal/plan/index.tsx
  src/components/sidebar/classifier/ClassifierTitle.tsx
  src/stories/modals/PlanModal.stories.tsx
  src/styles/planModal.ts
Labels: FEATURE

#53 일정 Type 통일화 및 일부 이름 리팩토링
  src/components/calendars/large/CalendarView.tsx
  src/components/plan/month/PlanViewUnit.tsx
  src/components/timetable/index.tsx
  src/hooks/usePlanDrag.ts
  src/stores/plan/focusedPlan.ts
  src/types/index.d.ts
  src/types/rq/plan.d.ts
  src/utils/compareObjects.ts
  src/utils/getCalendarPlans.ts
  src/utils/mock.ts
  src/utils/plan/day/divideDayPlans.ts
  src/utils/plan/day/isTimePlan.ts
  src/utils/plan/planViewHandlerToMonth.ts
Labels: REFACTOR

#55 axios response type 변경
  src/apis/axios/index.ts
  src/apis/axios/refresh.ts
  src/apis/user.ts
  src/hooks/useLogin.ts
Labels: REFACTOR

#56 Utils 폴더 정리 및 일정 컴포넌트 이름 리팩토링
  src/components/calendars/large/CalendarCell.tsx
  src/components/calendars/large/CalendarPlanLayer.tsx
  src/components/calendars/large/CalendarPlans.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/calendars/small/CalendarView.tsx
  src/components/calendars/small/index.tsx
  src/components/common/IconFrameComponent.tsx
  src/components/common/calendar/CalendarDay.tsx
  src/components/common/calendar/CalendarHeader/HeaderButtons.tsx
  src/components/icons/ChevronIcon.tsx
  src/components/icons/index.ts
  src/components/modal/plan/Hovered/index.tsx
  src/components/modal/plan/PlanTag.tsx
  src/components/plan/DayPlan.tsx
  src/components/plan/TimePlan.tsx
  src/components/timetable/TimetableAllDay.tsx
  src/components/timetable/index.tsx
  src/components/timetable/view/TimetablePlanColumn.tsx
  src/constants/mock.ts
  src/constants/rqKeys.ts
  src/hooks/rq/category.ts
  src/stores/date/index.ts
  src/stories/timetable/DayTimeTable.stories.tsx
  src/types/index.d.ts
  src/utils/calendar/dayHandler.ts
  src/utils/calendar/getCalendarInfo.ts
  src/utils/calendar/getCalendarPlans.ts
  src/utils/calendar/getDayClassName.ts
  src/utils/calendar/getPositionByViewPort.ts
  src/utils/calendar/monthHandler.ts
  src/utils/compareStoreDateToCalendarInfo.ts
  src/utils/date/compareDate.ts
Labels: REFACTOR

#57 카테고리, 태그 API 연결
  src/apis/category.ts
  src/apis/tag.ts
  src/components/modal/plan/PlanCategory.tsx
  src/components/modal/plan/PlanTag.tsx
  src/components/modal/plan/category/CategoryCreateForm.tsx
  src/components/sidebar/CategoryClassifier.tsx
  src/constants/mock.ts
  src/hooks/rq/category.ts
Labels: FEATURE

#62 Calendar와 Timetable 모두에서 사용할 수 있도록 Plan View 로직 분리
  src/plan/Plan.ts
  src/plan/PlanManager.ts
  src/plan/TimePlanManager.ts
  src/stories/plan/createPlanMock.ts
  src/stories/timetable/DayTimetable.stories.tsx
  src/stories/timetable/WeekTimetable.stories.tsx
  src/utils/plan/day/getOrderTimePlansInfo.ts
  src/utils/plan/day/sortPlans.ts
  src/utils/plan/day/sortTimePlans.ts
Labels: FEATURE, REFACTOR

#63 Timetable의 View 기능을 Plan Manager Class로 이전
  src/components/plan/TimePlan.tsx
  src/components/timetable/TimetableAllDay.tsx
  src/components/timetable/index.tsx
  src/components/timetable/view/TimetablePlanColumn.tsx
  src/components/timetable/view/TimetableTimeline.tsx
  src/components/timetable/view/index.tsx
  src/plan/Plan.ts
  src/plan/TimePlanManager.ts
  src/stories/plan/createPlanMock.ts
  src/stories/timetable/DayTimetable.stories.tsx
  src/stories/timetable/WeekTimetable.stories.tsx
  src/types/rq/plan.d.ts
  src/utils/date/getTimeString.ts
  src/utils/plan/day/divideDayPlans.ts
  src/utils/plan/day/getOrderTimePlansInfo.ts
  src/utils/plan/day/isTimePlan.ts
  src/utils/plan/day/sortPlans.ts
  src/utils/plan/divideTimePlans.ts
Labels: BUG, REFACTOR

#67 일정 Drag, Hover 시 사용하는 Hook에서 Plan Class를 사용하도록 변경
  src/components/calendars/large/CalendarPlans.tsx
  src/components/plan/DayPlan.tsx
  src/constants/mock.ts
  src/stores/plan/focusedPlan.ts
  src/stores/plan/hoveredPlan.ts
  src/stories/plan/createPlanMock.ts
Labels: REFACTOR

#68 Class를 통한 PlanView Refactoring
  src/components/calendars/large/CalendarCell.tsx
  src/components/calendars/large/CalendarLayer.tsx
  src/components/calendars/large/CalendarOverlay.tsx
  src/components/calendars/large/CalendarPlanLayer.tsx
  src/components/calendars/large/CalendarPlans.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/calendars/large/CalendarWeek.tsx
  src/components/plan/DayPlan.tsx
  src/plan/DaysPlanManager.ts
  src/types/rq/plan.d.ts
  src/utils/calendar/dayHandler.ts
  src/utils/calendar/getCalendarPlans.ts
  src/utils/plan/getDaysPlanManager.ts
Labels: FEATURE, REFACTOR

#72 Plan Class 의 속성 값을 올바르게 사용할 수 있도록 수정
  src/plan/Plan.ts
  src/stores/plan/focusedPlan.ts
  src/types/rq/plan.d.ts
  src/utils/plan/planViewHandlerToMonth.ts
Labels: BUG

#75 드래그를 통해 새로운 시간 일정을 생성하는 뷰를 보여주기
  src/components/plan/TimePlan.tsx
  src/components/timetable/view/TimetableCellColumn.tsx
  src/components/timetable/view/TimetableSelect.tsx
  src/components/timetable/view/index.tsx
  src/hooks/usePlanDrag.ts
  src/plan/TimePlanManager.ts
  src/stores/plan/focusedPlan.ts
  src/utils/date/getTimeMinute.ts
  src/utils/plan/getFocusedTimePlan.ts
Labels: FEATURE
