Repository JiPyoTak/plandar-client, pull requests merged in 2023-04, with the labels that each got.

#10 일/주/월 버튼 구현
  .storybook/preview.js
  .storybook/preview.jsx
  src/components/buttons/CalendarUnitButton.tsx
  src/stores/date/calendarUnit.ts
  src/stories/buttons/CalendarUnitButton.stories.tsx
  src/types/index.ts
  src/types/union.d.ts
  src/utils/constants.ts
Labels: FEATURE

#13 Stylish, Tag 버튼 구현
  .storybook/main.js
  src/assets/cross-icon.svg
  src/components/buttons/DirectionButtons.tsx
  src/components/buttons/PlusButton.tsx
  src/components/buttons/StylishButton.tsx
  src/components/buttons/TagButton.tsx
  src/components/buttons/TodayButton.tsx
  src/components/icons/index.ts
  src/stories/buttons/DirectionButtons.stories.tsx
  src/stories/buttons/PlusButton.stories.tsx
  src/stories/buttons/StylishButton.stories.tsx
  src/stories/buttons/TagButton.stories.tsx
  src/stories/buttons/TodayButton.stories.tsx
  src/styles/theme.ts
  src/types/index.ts
Labels: FEATURE

#17 메인 캘린더 생성 및 달력 헤더 구현
  src/components/Logo.tsx
  src/components/buttons/CalendarUnitButton.tsx
  src/components/buttons/DirectionButtons.tsx
  src/components/buttons/StylishButton.tsx
  src/components/buttons/TodayButton.tsx
  src/components/calendars/large/CalendarCell.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/calendars/large/CeilContent.tsx
  src/components/calendars/large/index.tsx
  src/components/calendars/small/CalendarBody.tsx
  src/components/calendars/small/CalendarHeader.tsx
  src/components/calendars/small/CalendarView.tsx
  src/components/calendars/small/index.tsx
  src/components/common/calendar/CalendarDay.tsx
  src/components/common/calendar/CalendarHeader/HeaderButtons.tsx
  src/components/common/calendar/CalendarHeader/HeaderTitle.tsx
  src/components/common/calendar/CalendarHeader/index.tsx
  src/components/common/calendar/DayOfWeek.tsx
  src/components/sidebar/index.tsx
  src/pages/index.tsx
  src/stores/date/calendarUnit.ts
  src/stores/date/index.ts
  src/stories/calendars/LargeCalendar.stories.tsx
  src/types/index.ts
  src/utils/compareDays.ts
  src/utils/compareStoreDateToCalendarInfo.ts
  src/utils/dayHandler.ts
  src/utils/getCalendarInfo.ts
  src/utils/getDayClassName.ts
  src/utils/monthHandler.ts
Labels: FEATURE, REFACTOR

#23 카테고리 생성 모달
  .storybook/preview-body.html
  .storybook/preview.jsx
  index.html
  src/assets/search-icon.svg
  src/components/buttons/CalendarUnitButton.tsx
  src/components/buttons/StylishButton.tsx
  src/components/common/ColorPicker.tsx
  src/components/common/Input.tsx
  src/components/icons/index.ts
  src/components/modal/CategoryModal.tsx
  src/components/modal/index.tsx
  src/components/sidebar/CategoryClassifier.tsx
  src/components/sidebar/classifier/ClassifierItem.tsx
  src/hooks/rq/category.ts
  src/stories/common/ColorPicker.stories.tsx
  src/stories/common/Input.stories.tsx
  src/stories/modals/CategoryModal.stories.tsx
  src/styles/theme.ts
  src/types/index.ts
  src/types/rq/category.d.ts
  src/utils/constants.ts
  src/utils/mock.ts
  src/utils/rqKeys.ts
Labels: FEATURE

#25 체크박스, 메모 컴포넌트 구현
  src/assets/memo-icon.svg
  src/components/buttons/Checkbox.tsx
  src/components/common/dropdown/index.tsx
  src/components/icons/index.ts
  src/components/modal/plan/PlanMemo.tsx
  src/components/sidebar/classifier/ClassifierTitle.tsx
  src/constants/index.ts
  src/constants/plan.ts
  src/stories/buttons/Checkbox.stories.tsx
  src/stories/plan/PlanMemo.stories.tsx
Labels: FEATURE

#28 theme의 타입 정의 제거
  src/styles/theme.ts
Labels: BUG

#24 일 단위 큰 달력 스타일 및 렌더링
  src/components/calendars/large/index.tsx
  src/components/sidebar/index.tsx
  src/components/timetable/TimetableAllDay.tsx
  src/components/timetable/TimetableHeader.tsx
  src/components/timetable/index.tsx
  src/components/timetable/view/TiemtableViewColumn.tsx
  src/components/timetable/view/TimetableCell.tsx
  src/components/timetable/view/TimetableTimeline.tsx
  src/components/timetable/view/index.tsx
  src/constants/index.ts
  src/constants/timetable.ts
  src/pages/index.tsx
  src/stories/timetable/Timetable.stories.tsx
  src/styles/home.ts
  src/styles/timetable.ts
Labels: FEATURE

#30 Input 컴포넌트 버그 해결
  src/components/common/Input.tsx
Labels: BUG

#29 일정을 달력에 그리기 위한 로직 구현
  src/components/Logo.tsx
  src/components/logo/index.tsx
  src/pages/index.tsx
  src/styles/GlobalStyle.tsx
  src/types/index.ts
  src/types/rq/plan.ts
  src/utils/dayHandler.ts
  src/utils/getCalendarInfo.ts
  src/utils/getCalendarPlans.ts
Labels: FEATURE

#34 일 단위 큰 달력에서 일정 렌더링 (시간)
  src/components/timetable/TimetableAllDay.tsx
  src/components/timetable/index.tsx
  src/components/timetable/view/TiemtableViewColumn.tsx
  src/components/timetable/view/TimetableCell.tsx
  src/components/timetable/view/TimetableCellColumn.tsx
  src/components/timetable/view/TimetablePlan.tsx
  src/components/timetable/view/TimetablePlanColumn.tsx
  src/components/timetable/view/TimetableTimeline.tsx
  src/components/timetable/view/index.tsx
  src/pages/index.tsx
  src/stores/date/calendarUnit.ts
  src/stories/timetable/DayTimeTable.stories.tsx
  src/stories/timetable/WeekTimetable.stories.tsx
  src/types/index.d.ts
  src/types/rq/plan.d.ts
  src/utils/color.ts
  src/utils/mock.ts
  src/utils/plan/day/divideDayPlans.ts
  src/utils/plan/day/getOrderTimePlansInfo.ts
  src/utils/plan/day/sortTimePlans.ts
  src/utils/timeToString.ts
Labels: FEATURE, REFACTOR

#36 월 달력 일정 드래그 기능 구현
  package.json
  src/components/calendars/large/CalendarCell.tsx
  src/components/calendars/large/CalendarLayer.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/calendars/large/CeilContent.tsx
  src/components/calendars/large/index.tsx
  src/components/common/calendar/CalendarDay.tsx
  src/components/plan/month/PlanViewUnit.tsx
  src/components/plan/month/index.tsx
  src/hooks/drag/useDrag.ts
  src/stores/plan/hoverdPlan.ts
  src/stores/plan/selectedPlan.ts
  src/utils/compareObjects.ts
  src/utils/plan/dummy.ts
  src/utils/plan/planViewHandlerToMonth.ts
Labels: FEATURE

#33 일정생성 모달의 태그 선택 컴포넌트 구현
  src/assets/category-icon.svg
  src/assets/tag-icon.svg
  src/components/icons/index.ts
  src/components/modal/plan/Candidates/CandidateItem.tsx
  src/components/modal/plan/Candidates/CandidateList.tsx
  src/components/modal/plan/Candidates/index.ts
  src/components/modal/plan/PlanTag.tsx
  src/constants/plan.ts
  src/hooks/useDebounce.ts
  src/stories/plan/PlanTag.stories.tsx
  src/types/rq/tag.d.ts
  src/utils/mock.ts
Labels: FEATURE

#40 일정생성 모달창의 카테고리 부분 구현
  src/components/icons/index.ts
  src/components/modal/plan/Candidates/CandidateItem.tsx
  src/components/modal/plan/CategoryCreateForm.tsx
  src/components/modal/plan/PlanCategory.tsx
  src/hooks/rq/category.ts
  src/stories/plan/PlanCategory.stories.tsx
  src/utils/mock.ts
Labels: FEATURE

#44 Timetable 일부 코드 개선 및 CellColumn Hover 기능 변경
  src/components/timetable/TimetableHeader.tsx
  src/components/timetable/view/TimetableCellColumn.tsx
  src/components/timetable/view/TimetablePlan.tsx
  src/components/timetable/view/TimetableTimeline.tsx
  src/styles/timetable.ts
  src/utils/date/getTimeString.ts
Labels: FEATURE, REFACTOR

#42 ClassifierTitle에 각 표시기능 구현 및 오동작 해결
  src/components/common/ColorPicker.tsx
  src/components/common/dropdown/DropdownController.tsx
  src/components/modal/CategoryModal.tsx
  src/components/modal/plan/PlanCategory.tsx
  src/components/modal/plan/PlanMemo.tsx
  src/components/modal/plan/PlanTag.tsx
  src/components/modal/plan/category/CategoryCreateForm.tsx
  src/components/modal/plan/category/SelectedCategoryDisplay.tsx
  src/components/sidebar/CategoryClassifier.tsx
  src/components/sidebar/classifier/ClassifierTitle.tsx
  src/constants/plan.ts
  src/stories/common/ColorPicker.stories.tsx
  src/styles/planModal.ts
Labels: BUG, FEATURE

#48 Storybook에서 Calendar 동작이 잘 안먹히던 버그 수정
  src/stores/date/calendarUnit.ts
  src/stories/calendars/LargeCalendar.stories.tsx
  src/stories/calendars/SmallCalendar.stories.tsx
Labels: BUG, FEATURE

#46 useDrag 훅과 selectedPlan을 Timetable에서 사용할 수 있도록 일부 변경
  src/components/calendars/large/CalendarLayer.tsx
  src/components/calendars/large/CalendarView.tsx
  src/components/plan/month/PlanViewUnit.tsx
  src/components/plan/month/index.tsx
  src/components/timetable/view/TimetableCellColumn.tsx
  src/components/timetable/view/index.tsx
  src/hooks/drag/useDrag.ts
  src/hooks/usePlanDrag.ts
  src/stores/date/calendarUnit.ts
  src/stores/plan/focusedPlan.ts
  src/stores/plan/selectedPlan.ts
  src/stories/calendars/LargeCalendar.stories.tsx
  src/stories/calendars/SmallCalendar.stories.tsx
  src/stories/timetable/DayTimeTable.stories.tsx
  src/utils/date/getTimeString.ts
  src/utils/padZero.ts
  src/utils/plan/planViewHandlerToMonth.ts
Labels: FEATURE, REFACTOR
