Repository JiPyoTak/plandar-client, pull requests merged in 2023-09, with the labels that each got.

#170 Electron을 이용해 Desktop App을 배포할 수 있도록 설정
  .eslintignore
  .github/workflows/deploy.yml
  .gitignore
  electron.js
  index.html
  package-lock.json
  package.json
  public/images/android-icon-512x512.ico
  public/images/apple-icon-512x512.icns
Labels: CHORE

#171 React Query 코드 컨벤션 통일화 및 일부 버그 수정
  src/components/home/main/timetable/view/columns/TimetableSelected.tsx
  src/components/modal/category/index.tsx
  src/components/modal/plan/create/category/CategoryCreateForm.tsx
  src/components/modal/plan/create/category/SelectedCategoryDisplay.tsx
  src/components/modal/plan/create/index.tsx
  src/components/modal/plan/select/index.tsx
  src/constants/queryKey.ts
  src/constants/rqKeys.ts
  src/hooks/query/category.ts
  src/hooks/query/plan.ts
  src/hooks/usePlanDrag.ts
  src/hooks/useRangedPlans.ts
  src/stories/calendars/LargeCalendar.stories.tsx
  src/stories/sidebar/CategoryClassifier.stories.tsx
  src/stories/sidebar/TagClassifier.stories.tsx
  src/stories/sidebar/TypeClassifier.stories.tsx
  src/stories/timetable/DayTimetable.stories.tsx
  src/stories/timetable/WeekTimetable.stories.tsx
  src/utils/plan/createInitPlan.ts
Labels: BUG, REFACTOR

#172 submit시 modal onCloseHandler 실행
  src/components/modal/plan/create/index.tsx
Labels: FEATURE

#178 카테고리 삭제 실패시 toast 메시지 올바르게 뜨도록 해결
  src/components/modal/category/index.tsx
Labels: BUG

#181 HoveredPlan에 종료 시각도 보이도록 변경
  src/components/common/modal/Timestamp.tsx
Labels: BUG

#182 Timetable 스크롤, Tag Skeleton View 버그 수정 및 날짜 및 시간 선택 스타일 변경
  src/components/home/main/timetable/TimetableScroll.tsx
  src/components/home/main/timetable/index.tsx
  src/components/home/sidebar/content/classifier/TagClassifier.tsx
  src/components/modal/plan/create/plan-date/DatePicker.tsx
  src/components/modal/plan/create/plan-date/TimeInput.tsx
  src/styles/scroll.ts
  src/styles/timetable.ts
Labels: BUG, FEATURE

#180 월 달력에서 일정 렌더링시 날짜차이가 날 경우 종일 일정으로 렌더링하도록 변경
  src/components/home/main/timetable/view/TimetableAllDay.tsx
  src/components/home/sidebar/SidebarIcons.tsx
  src/components/toast/ToastContainer.tsx
  src/core/plan/DaysPlanManager.ts
  src/hooks/usePlanPreviewEvent.ts
  src/utils/plan/divideTimePlans.ts
Labels: BUG, REFACTOR

#183 0915 1차 유지 보수
  src/components/common/modal/Timestamp.tsx
  src/components/home/main/timetable/TimetableScroll.tsx
  src/components/home/main/timetable/index.tsx
  src/components/home/main/timetable/view/TimetableAllDay.tsx
  src/components/home/sidebar/SidebarIcons.tsx
  src/components/home/sidebar/content/classifier/TagClassifier.tsx
  src/components/modal/category/index.tsx
  src/components/modal/plan/create/plan-date/DatePicker.tsx
  src/components/modal/plan/create/plan-date/TimeInput.tsx
  src/components/toast/ToastContainer.tsx
  src/core/plan/DaysPlanManager.ts
  src/hooks/usePlanPreviewEvent.ts
  src/styles/scroll.ts
  src/styles/timetable.ts
  src/utils/plan/divideTimePlans.ts
Labels: REFACTOR

#185 사용자 사진이 보이지 않던 버그 수정
  index.html
Labels: BUG

#186 사용자 사진이 보이지 않던 버그 수정 후 배포
  index.html
Labels: BUG
